### ISSUE TITLE
Support for Rails 7?

### ISSUE THREAD

**Issue by sasharevzin** [jetrockets/activerecord-update_counters_with_values#1]
Doesn't look like it works for Rails 7

**Comment by igor-alexandrov** [comment]
Will take a look, thanks!

**Comment by sasharevzin** [comment]
I found the issue. In the prev Rails versions, you could send the record like `User.increment_counter_and_return_value(user, :views)`. Now you need to set id expicently like `User.increment_counter_and_return_value(user.id, :views)`.

Sorry to bother :homer_disappearing:
